### ISSUE TITLE
Publish appveyor.yml and deploy to GitHub

### ISSUE THREAD

**Issue by EwoutH** [joedrago/colorist#20]
It would be nice if the AppVeyor configuration got published in a `appveyor.yml` file, then it also works on forks and can be viewed and modified by everyone.

I would also like a deploy to GitHub function, so that colorist.exe gets attached to each [release](https://github.com/joedrago/colorist/releases/tag/v0.0.43).

Example YML 
```
deploy:
  - provider: GitHub
    artifact: build\bin\colorist\Release\colorist.exe
    auth_token:
      secure: 'hY5Mk6KOwgQ97TzEBsM7Woqr1ZIm5QTvHg8EvxMV1x8j3wk/3mNBMqWFFbEIBK0i'
    prerelease: true
    on:
      appveyor_repo_tag: true
```
Secure token needs to be changed:
> To enable uploading to GitHub Releases, a maintainer needs to update this patch with his personal authentication token. You can generate one on https://github.com/settings/tokens/new (select public_repo as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 21 (after secure:) in the appveyor.yml file.
